---
name: 运维审批
option:
  - describe: 运维审批人
    name: opapprover
    type: input
    value: ""

template_argv:
  approver: ${opapprover}
  title:    "BPM/${_bpmuuid_}/注册域名"
  content:  "\n申请人:${_user_}\n域名:${x.domain}\nBPM单号:${_bpmuuid_}\n申请理由:${x.note}"
