---
name: 运维审批
option:
  - describe: 运维审批人
    name: opapprover
    type: input
    value: ""

template_argv:
  approver: ${opapprover}
  title:    "BPM/${_bpmuuid_}/资源申请/腾讯云/CVM"
  content:  "申请人:${_user_} BPM单号: ${_bpmuuid_}"
