---
name: '业务负责人审批'
option:
  - describe: 业务审批人
    name: oaapprover
    type: input
    value: ""

template_argv:
  approver: ${oaapprover}
  title:    "BPM/${_bpmuuid_}/资源申请/腾讯云/CVM"
  content:  "申请人:${_user_} BPM单号: ${_bpmuuid_}"
